version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jschool504"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm"
      - "dependencies"
